# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-rubycw/all/rubocop-rubycw.rbi
#
# rubocop-rubycw-0.2.2

module RuboCop
end
module RuboCop::Rubycw
end
class RuboCop::Rubycw::Error < StandardError
end
class RuboCop::Rubycw::Plugin < LintRoller::Plugin
  def about; end
  def rules(_context); end
  def supported?(context); end
end
module RuboCop::Rubycw::WarningCapturer
  def self.capture(source); end
  def self.start; end
  def self.stop; end
  def self.warnings; end
end
module Warning
  def self.warn(*message, **kwargs); end
end
module RuboCop::Cop
end
module RuboCop::Cop::Rubycw
end
class RuboCop::Cop::Rubycw::Rubycw < RuboCop::Cop::Base
  def on_new_investigation; end
  def warnings(source); end
  include RuboCop::Cop::RangeHelp
end
