# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yard/all/yard.rbi
#
# yard-0.9.37

module YARD
end
class YARD::RubygemsHook
  def force; end
  def force=(arg0); end
  def generate; end
  def generate_yard; end
  def generate_yard=(arg0); end
  def generate_yri; end
  def generate_yri=(arg0); end
  def initialize(spec, generate_yard = nil, generate_yri = nil); end
  def install_yard; end
  def install_yri; end
  def remove; end
  def run_yardoc(*args); end
  def self.generation_hook(installer, specs); end
  def self.load_yard; end
  def self.removal_hook(uninstaller); end
  def self.yard_version; end
  def setup; end
  def uninstall_yard; end
  def uninstall_yri; end
  extend Gem::UserInteraction
  include Gem::UserInteraction
end
